name: Jenkinsfile Runner CI
'on':
  push:
    branches:
      - master
jobs:
  jenkinsfile-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Execute Jenkinsfile
        uses: jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
