name: Jenkinsfile Runner CI
'on':
  push:
    branches:
      - master
jobs:
  jenkinsfile-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Execute Jenkinsfile
        uses: sirine707/mock-company-webapp/Jenkinsfile@master
        with:
          jenkinsfile: Jenkinsfile
